### PR TITLE
timesync epoch helpers

### PR DESCRIPTION
**Pull request by amfern**
@Acuadros95 I tried using the API you added at #117 but its not working for me as well as the eProsima, mainly because i can use 0 timeout and get the epoch time even if timeout reached,

I propose to wrap the eProsima API as follows

### CODE REVIEW

**Comment by pablogs9** [comment]
@Acuadros95 can you take care of this?

Tests are failing.

**Comment by amfern** [comment]
Thanks for fixing the tests @Acuadros95

**Comment by pablogs9** [comment]
@Acuadros95 LGTM, squash merge if you are ok

**Review by pablogs9 — APPROVED** [review]

**Comment by Acuadros95** [comment]
Marie Kondo

**Comment by Acuadros95** [comment]
@amfern I have included a check for session synchronized on the rmw_uros_epoch functions.

I think it looks great, thanks for your suggestions.

**Review by Acuadros95 — APPROVED** [review]

**Comment by amfern** [comment]
yes, this works perfectly with my code, thanks!

**Pull request merged**
