### PR TITLE
Add time sync functionality

### PR DESCRIPTION
**Pull request by Acuadros95**

### CODE REVIEW

**Review by jamoralp — COMMENTED** [review]
Looks nice. I think we should include an unitary test too

**Comment by pablogs9** [comment]
Marie Kondo

**Comment by Acuadros95** [comment]
Added unitary test, testing timestamp sync with a precision of 1 second

**Comment by pablogs9** [comment]
Marie Kondo

**Review by jamoralp — APPROVED** [review]

**Pull request merged**
